title: Shannon Gold - Technical Writing Samples
description: Technical Writing Samples

plugins:
  - jekyll-remote-theme

remote_theme: "jekyll/minima@1e8a445"

url: https://shango.github.io

# aux_links:
#   Template Repository: https://github.com/shango/shango.github.io
