title: Shannon Gold
description: Technical Writing Samples

remote_theme: just-the-docs/just-the-docs

url: https://shango.github.io

plugins:
  - jekyll-remote-theme

# aux_links:
#   Template Repository: https://github.com/shango/shango.github.io

just_the_docs:
  navigation:
    structure: nested